apiVersion: apps/v1
kind: Deployment
metadata:
  name: population-api-deployment
  labels:
    app: population-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: population-api
  template:
    metadata:
      labels:
        app: population-api
    spec:
      containers:
      - name: population-api-container
        image: makman005/populationapi:latest
        ports:
        - containerPort: 9696
